name = "OpenBlox"
license = "GPLv3+"
licenselink = "https://www.gnu.org/licenses/gpl.html"
description = "A theme for the OpenBlox project website"
homepage = "https://git.openblox.org/openblox/openblox-hugo-theme"
min_version = "0.30.2"
